# Generated by Django 4.0.4 on 2022-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0005_alter_project_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presentation',
            field=models.FileField(upload_to='presentations'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
