# Generated by Django 4.0.4 on 2022-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0002_alter_video_project'),
        ('silsite', '0006_alter_project_presentation_alter_video_video'),
    ]

    operations = [
    ]
