# Generated by Django 4.0.3 on 2022-06-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0007_merge_20220608_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_text',
            field=models.FileField(upload_to='short_texts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.FileField(upload_to='texts'),
        ),
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='silsite.project'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
