# Generated by Django 4.0.4 on 2022-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0008_alter_project_name_alter_project_short_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
