# Generated by Django 4.0.4 on 2022-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0010_alter_video_id_alter_video_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
