# Generated by Django 4.0.5 on 2022-06-15 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0010_alter_video_id_alter_video_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presentation',
            field=models.FileField(upload_to='presentations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text',
            field=models.FileField(upload_to='short_texts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.FileField(upload_to='texts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
