# Generated by Django 4.0.4 on 2022-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=123, max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=511),
        ),
    ]
