# Generated by Django 4.0.4 on 2022-06-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0002_project_name_alter_project_short_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='presentation',
        ),
    ]
