# Generated by Django 4.0.4 on 2022-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silsite', '0003_remove_project_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation',
            field=models.FileField(default=1, upload_to='./../presentations/'),
            preserve_default=False,
        ),
    ]
